package bisaPetcah.view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import bisaPetcah.auth.Auth;
import bisaPetcah.model.Design;
import bisaPetcah.model.divisi.DivisiService;
import bisaPetcah.model.member.MemberService;

/**
 * @author bisa_petcah
 */
public class Dashboard extends javax.swing.JFrame {
    MemberService memberService = new MemberService();
    DivisiService divisiService = new DivisiService();
            

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        initUsername();
        initData();
    }
    
    public void initUsername() {
        tvUsername.setText(Auth.getNama());
    }

    public void initData() {
        tvTotalAnggota.setText(String.valueOf(memberService.countAll()));
        tvAnggotaAktif.setText(String.valueOf(memberService.countWhere("status = 'Aktif'")));
        tvAnggotaPasif.setText(String.valueOf(memberService.countWhere("status = 'Pasif'")));
        tvDivisi.setText(String.valueOf(divisiService.countAll()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        tvUsername = new javax.swing.JLabel();
        tvRole = new javax.swing.JLabel();
        panelSideBarMenu = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        btnTotalAnggota = new javax.swing.JPanel();
        txtTotalAnggota = new javax.swing.JLabel();
        btnAnggotaAktif = new javax.swing.JPanel();
        txtAnggotaAktif = new javax.swing.JLabel();
        btnAnggotaPasif = new javax.swing.JPanel();
        txtAnggotaPasif = new javax.swing.JLabel();
        btnDivisi = new javax.swing.JPanel();
        txtDivisi = new javax.swing.JLabel();
        panelLog = new javax.swing.JPanel();
        btnLogout = new javax.swing.JPanel();
        txtLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoArchev = new javax.swing.JLabel();
        panelTotalAnggota = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        countJumlahTotalAnggota = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        tvTotalAnggota = new javax.swing.JLabel();
        tvStatus = new javax.swing.JLabel();
        panelAnggotaAktif = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        countJumlahAnggotaAktif = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        tvAnggotaAktif = new javax.swing.JLabel();
        panelAnggotaPasif = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        countJumlahAnggotaPasif = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        tvAnggotaPasif = new javax.swing.JLabel();
        panelDivisi = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        countJumlahDivisi = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        tvDivisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArChev");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(229, 229, 229));

        tvUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tvUsername.setText("Username");

        tvRole.setText("Admin");

        panelSideBarMenu.setBackground(new java.awt.Color(153, 153, 153));

        panelInput.setBackground(new java.awt.Color(255, 255, 255));

        btnDashboard.setBackground(new java.awt.Color(248, 164, 0));

        txtDashboard.setBackground(new java.awt.Color(255, 255, 255));
        txtDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-dashboard.png"))); // NOI18N
        txtDashboard.setText("Dashboard");

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnTotalAnggota.setBackground(new java.awt.Color(255, 255, 255));
        btnTotalAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTotalAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTotalAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTotalAnggotaMouseExited(evt);
            }
        });

        txtTotalAnggota.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalAnggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-people.png"))); // NOI18N
        txtTotalAnggota.setText("Total Anggota");

        javax.swing.GroupLayout btnTotalAnggotaLayout = new javax.swing.GroupLayout(btnTotalAnggota);
        btnTotalAnggota.setLayout(btnTotalAnggotaLayout);
        btnTotalAnggotaLayout.setHorizontalGroup(
            btnTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTotalAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTotalAnggotaLayout.setVerticalGroup(
            btnTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTotalAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalAnggota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAnggotaAktif.setBackground(new java.awt.Color(255, 255, 255));
        btnAnggotaAktif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnggotaAktifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnggotaAktifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnggotaAktifMouseExited(evt);
            }
        });

        txtAnggotaAktif.setBackground(new java.awt.Color(255, 255, 255));
        txtAnggotaAktif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAnggotaAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-people.png"))); // NOI18N
        txtAnggotaAktif.setText("Anggota Aktif");

        javax.swing.GroupLayout btnAnggotaAktifLayout = new javax.swing.GroupLayout(btnAnggotaAktif);
        btnAnggotaAktif.setLayout(btnAnggotaAktifLayout);
        btnAnggotaAktifLayout.setHorizontalGroup(
            btnAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAnggotaAktifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAnggotaAktif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAnggotaAktifLayout.setVerticalGroup(
            btnAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAnggotaAktifLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAnggotaAktif)
                .addContainerGap())
        );

        btnAnggotaPasif.setBackground(new java.awt.Color(255, 255, 255));
        btnAnggotaPasif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnggotaPasifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnggotaPasifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnggotaPasifMouseExited(evt);
            }
        });

        txtAnggotaPasif.setBackground(new java.awt.Color(255, 255, 255));
        txtAnggotaPasif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAnggotaPasif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-people.png"))); // NOI18N
        txtAnggotaPasif.setText("Anggota Pasif");

        javax.swing.GroupLayout btnAnggotaPasifLayout = new javax.swing.GroupLayout(btnAnggotaPasif);
        btnAnggotaPasif.setLayout(btnAnggotaPasifLayout);
        btnAnggotaPasifLayout.setHorizontalGroup(
            btnAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAnggotaPasifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAnggotaPasif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAnggotaPasifLayout.setVerticalGroup(
            btnAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnggotaPasifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAnggotaPasif, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDivisi.setBackground(new java.awt.Color(255, 255, 255));
        btnDivisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivisiMouseExited(evt);
            }
        });

        txtDivisi.setBackground(new java.awt.Color(255, 255, 255));
        txtDivisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDivisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-divisi.png"))); // NOI18N
        txtDivisi.setText("Divisi");

        javax.swing.GroupLayout btnDivisiLayout = new javax.swing.GroupLayout(btnDivisi);
        btnDivisi.setLayout(btnDivisiLayout);
        btnDivisiLayout.setHorizontalGroup(
            btnDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDivisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDivisi, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );
        btnDivisiLayout.setVerticalGroup(
            btnDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDivisiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDivisi)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnggotaAktif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTotalAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnggotaPasif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTotalAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnggotaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnggotaPasif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLog.setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        txtLogout.setBackground(new java.awt.Color(255, 255, 255));
        txtLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/icon-logout.png"))); // NOI18N
        txtLogout.setText("Logout");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoArchev.setBackground(new java.awt.Color(255, 255, 255));
        logoArchev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoArchev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/ArChev-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoArchev, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(logoArchev, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panelSideBarMenuLayout = new javax.swing.GroupLayout(panelSideBarMenu);
        panelSideBarMenu.setLayout(panelSideBarMenuLayout);
        panelSideBarMenuLayout.setHorizontalGroup(
            panelSideBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarMenuLayout.createSequentialGroup()
                .addGroup(panelSideBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        panelSideBarMenuLayout.setVerticalGroup(
            panelSideBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideBarMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTotalAnggota.setBackground(new java.awt.Color(248, 164, 0));
        panelTotalAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTotalAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTotalAnggotaMouseExited(evt);
            }
        });

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/dashboard/people-white.png"))); // NOI18N

        countJumlahTotalAnggota.setBackground(new java.awt.Color(255, 255, 255));
        countJumlahTotalAnggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countJumlahTotalAnggota.setForeground(new java.awt.Color(255, 255, 255));
        countJumlahTotalAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countJumlahTotalAnggota.setText("Jumlah");

        Label.setBackground(new java.awt.Color(255, 255, 255));
        Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Total Anggota");

        tvTotalAnggota.setBackground(new java.awt.Color(255, 255, 255));
        tvTotalAnggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tvTotalAnggota.setForeground(new java.awt.Color(255, 255, 255));
        tvTotalAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvTotalAnggota.setText("14");

        javax.swing.GroupLayout panelTotalAnggotaLayout = new javax.swing.GroupLayout(panelTotalAnggota);
        panelTotalAnggota.setLayout(panelTotalAnggotaLayout);
        panelTotalAnggotaLayout.setHorizontalGroup(
            panelTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalAnggotaLayout.createSequentialGroup()
                .addGroup(panelTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTotalAnggotaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(countJumlahTotalAnggota))
                    .addGroup(panelTotalAnggotaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTotalAnggotaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tvTotalAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelTotalAnggotaLayout.setVerticalGroup(
            panelTotalAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countJumlahTotalAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvTotalAnggota)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        tvStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/tab/dashboard.png"))); // NOI18N

        panelAnggotaAktif.setBackground(new java.awt.Color(255, 255, 255));
        panelAnggotaAktif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnggotaAktifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnggotaAktifMouseExited(evt);
            }
        });

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/dashboard/people-grey.png"))); // NOI18N
        icon1.setText("jLabel1");

        countJumlahAnggotaAktif.setBackground(new java.awt.Color(255, 255, 255));
        countJumlahAnggotaAktif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countJumlahAnggotaAktif.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countJumlahAnggotaAktif.setText("Jumlah");

        Label1.setBackground(new java.awt.Color(255, 255, 255));
        Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("Anggota Aktif");

        tvAnggotaAktif.setBackground(new java.awt.Color(255, 255, 255));
        tvAnggotaAktif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tvAnggotaAktif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvAnggotaAktif.setText("14");

        javax.swing.GroupLayout panelAnggotaAktifLayout = new javax.swing.GroupLayout(panelAnggotaAktif);
        panelAnggotaAktif.setLayout(panelAnggotaAktifLayout);
        panelAnggotaAktifLayout.setHorizontalGroup(
            panelAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaAktifLayout.createSequentialGroup()
                .addGroup(panelAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnggotaAktifLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(countJumlahAnggotaAktif))
                    .addGroup(panelAnggotaAktifLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAnggotaAktifLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvAnggotaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelAnggotaAktifLayout.setVerticalGroup(
            panelAnggotaAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaAktifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countJumlahAnggotaAktif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvAnggotaAktif)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        panelAnggotaPasif.setBackground(new java.awt.Color(255, 255, 255));
        panelAnggotaPasif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnggotaPasifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnggotaPasifMouseExited(evt);
            }
        });

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/dashboard/people-grey.png"))); // NOI18N
        icon2.setText("jLabel1");

        countJumlahAnggotaPasif.setBackground(new java.awt.Color(255, 255, 255));
        countJumlahAnggotaPasif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countJumlahAnggotaPasif.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countJumlahAnggotaPasif.setText("Jumlah");

        Label2.setBackground(new java.awt.Color(255, 255, 255));
        Label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("Anggota Pasif");

        tvAnggotaPasif.setBackground(new java.awt.Color(255, 255, 255));
        tvAnggotaPasif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tvAnggotaPasif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvAnggotaPasif.setText("14");

        javax.swing.GroupLayout panelAnggotaPasifLayout = new javax.swing.GroupLayout(panelAnggotaPasif);
        panelAnggotaPasif.setLayout(panelAnggotaPasifLayout);
        panelAnggotaPasifLayout.setHorizontalGroup(
            panelAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaPasifLayout.createSequentialGroup()
                .addGroup(panelAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnggotaPasifLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(countJumlahAnggotaPasif))
                    .addGroup(panelAnggotaPasifLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAnggotaPasifLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvAnggotaPasif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelAnggotaPasifLayout.setVerticalGroup(
            panelAnggotaPasifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaPasifLayout.createSequentialGroup()
                .addComponent(icon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countJumlahAnggotaPasif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvAnggotaPasif)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        panelDivisi.setBackground(new java.awt.Color(255, 255, 255));
        panelDivisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDivisiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDivisiMouseExited(evt);
            }
        });

        icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisaPetcah/images/icon/dashboard/tas_divisi.png"))); // NOI18N
        icon3.setText("jLabel1");

        countJumlahDivisi.setBackground(new java.awt.Color(255, 255, 255));
        countJumlahDivisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countJumlahDivisi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countJumlahDivisi.setText("Jumlah");

        Label3.setBackground(new java.awt.Color(255, 255, 255));
        Label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setText("Divisi");

        tvDivisi.setBackground(new java.awt.Color(255, 255, 255));
        tvDivisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tvDivisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvDivisi.setText("14");

        javax.swing.GroupLayout panelDivisiLayout = new javax.swing.GroupLayout(panelDivisi);
        panelDivisi.setLayout(panelDivisiLayout);
        panelDivisiLayout.setHorizontalGroup(
            panelDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDivisiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(panelDivisiLayout.createSequentialGroup()
                .addGroup(panelDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDivisiLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(countJumlahDivisi))
                    .addGroup(panelDivisiLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tvDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelDivisiLayout.setVerticalGroup(
            panelDivisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countJumlahDivisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvDivisi)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(panelSideBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tvUsername)
                            .addComponent(tvRole, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DashboardLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DashboardLayout.createSequentialGroup()
                                        .addComponent(panelTotalAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelAnggotaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(DashboardLayout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(tvStatus)))
                        .addGap(79, 79, 79)
                        .addComponent(panelAnggotaPasif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(109, Short.MAX_VALUE))))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSideBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tvUsername)
                .addGap(1, 1, 1)
                .addComponent(tvRole)
                .addGap(31, 31, 31)
                .addComponent(tvStatus)
                .addGap(61, 61, 61)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAnggotaAktif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAnggotaPasif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(panelDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -30, 1550, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        Design.btnInActive(btnLogout);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        Design.btnHover(btnLogout);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        Auth.logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnDivisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiMouseExited
        Design.btnInActive(btnDivisi);
    }//GEN-LAST:event_btnDivisiMouseExited

    private void btnDivisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiMouseEntered
        Design.btnHover(btnDivisi);
    }//GEN-LAST:event_btnDivisiMouseEntered

    private void btnDivisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiMouseClicked
        Divisi divisi = new Divisi();
        divisi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDivisiMouseClicked

    private void btnAnggotaPasifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaPasifMouseExited
        Design.btnInActive(btnAnggotaPasif);
    }//GEN-LAST:event_btnAnggotaPasifMouseExited

    private void btnAnggotaPasifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaPasifMouseEntered
        Design.btnHover(btnAnggotaPasif);
    }//GEN-LAST:event_btnAnggotaPasifMouseEntered

    private void btnAnggotaPasifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaPasifMouseClicked
        AnggotaPasif anggotaPasif = new AnggotaPasif();
        anggotaPasif.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnggotaPasifMouseClicked

    private void btnAnggotaAktifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaAktifMouseExited
        Design.btnInActive(btnAnggotaAktif);
    }//GEN-LAST:event_btnAnggotaAktifMouseExited

    private void btnAnggotaAktifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaAktifMouseEntered
        Design.btnHover(btnAnggotaAktif);
    }//GEN-LAST:event_btnAnggotaAktifMouseEntered

    private void btnAnggotaAktifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaAktifMouseClicked
        AnggotaAktif anggotaAktif = new AnggotaAktif();
        anggotaAktif.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnggotaAktifMouseClicked

    private void btnTotalAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalAnggotaMouseExited
        Design.btnInActive(btnTotalAnggota);
    }//GEN-LAST:event_btnTotalAnggotaMouseExited

    private void btnTotalAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalAnggotaMouseEntered
        Design.btnHover(btnTotalAnggota);
    }//GEN-LAST:event_btnTotalAnggotaMouseEntered

    private void btnTotalAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalAnggotaMouseClicked
        TotalAnggota totalAnggota = new TotalAnggota();
        totalAnggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTotalAnggotaMouseClicked

    private void panelTotalAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTotalAnggotaMouseEntered
        Design.btnHover(panelTotalAnggota);
    }//GEN-LAST:event_panelTotalAnggotaMouseEntered

    private void panelTotalAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTotalAnggotaMouseExited
        Design.btnActive(panelTotalAnggota);
    }//GEN-LAST:event_panelTotalAnggotaMouseExited

    private void panelAnggotaAktifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnggotaAktifMouseEntered
        Design.btnHover(panelAnggotaAktif);
    }//GEN-LAST:event_panelAnggotaAktifMouseEntered

    private void panelAnggotaAktifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnggotaAktifMouseExited
        Design.btnInActive(panelAnggotaAktif);
    }//GEN-LAST:event_panelAnggotaAktifMouseExited

    private void panelAnggotaPasifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnggotaPasifMouseEntered
        Design.btnHover(panelAnggotaPasif);
    }//GEN-LAST:event_panelAnggotaPasifMouseEntered

    private void panelAnggotaPasifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnggotaPasifMouseExited
        Design.btnInActive(panelAnggotaPasif);
    }//GEN-LAST:event_panelAnggotaPasifMouseExited

    private void panelDivisiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDivisiMouseEntered
        Design.btnHover(panelDivisi);
    }//GEN-LAST:event_panelDivisiMouseEntered

    private void panelDivisiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDivisiMouseExited
        Design.btnInActive(panelDivisi);
    }//GEN-LAST:event_panelDivisiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JPanel btnAnggotaAktif;
    private javax.swing.JPanel btnAnggotaPasif;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnDivisi;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnTotalAnggota;
    private javax.swing.JLabel countJumlahAnggotaAktif;
    private javax.swing.JLabel countJumlahAnggotaPasif;
    private javax.swing.JLabel countJumlahDivisi;
    private javax.swing.JLabel countJumlahTotalAnggota;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoArchev;
    private javax.swing.JPanel panelAnggotaAktif;
    private javax.swing.JPanel panelAnggotaPasif;
    private javax.swing.JPanel panelDivisi;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelSideBarMenu;
    private javax.swing.JPanel panelTotalAnggota;
    private javax.swing.JLabel tvAnggotaAktif;
    private javax.swing.JLabel tvAnggotaPasif;
    private javax.swing.JLabel tvDivisi;
    private javax.swing.JLabel tvRole;
    private javax.swing.JLabel tvStatus;
    private javax.swing.JLabel tvTotalAnggota;
    private javax.swing.JLabel tvUsername;
    private javax.swing.JLabel txtAnggotaAktif;
    private javax.swing.JLabel txtAnggotaPasif;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtDivisi;
    private javax.swing.JLabel txtLogout;
    private javax.swing.JLabel txtTotalAnggota;
    // End of variables declaration//GEN-END:variables
}
